// Auto-generated by ts-rs. DO NOT EDIT.
// This file will be overwritten by `pnpm run generate-types`

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type AgentType = "claude_code";
export type AgentStatus = "idle" | "busy" | "error" | "offline";
export type AuthStatus = "unknown" | "authenticated" | "unauthenticated";
export type TaskStatus = "backlog" | "in_progress" | "waiting" | "done";
export type SessionStatus = "created" | "running" | "paused" | "completed" | "failed";
export type RepositoryRole = "primary" | "dependency";
export type WorktreeStatus = "active" | "stale" | "deleted";
export type LogType = "stdout" | "stderr" | "control" | "status" | "user_input";
export type WorkflowRunStatus = "running" | "paused" | "completed" | "failed";
export type WorkflowStepType = "plan" | "human_gate" | "implement" | "pr_review" | "human_review" | "complete_pr";
export type WorkflowStepStatus = "pending" | "running" | "waiting_for_human" | "completed" | "rejected" | "failed";

// ---------------------------------------------------------------------------
// Model structs
// ---------------------------------------------------------------------------

export interface Agent {
    id: string;
    name: string;
    agent_type: AgentType;
    executable_path?: string;
    status: AgentStatus;
    auth_status: AuthStatus;
    last_heartbeat?: string;
    created_at: string;
    updated_at: string;
}

export interface Task {
    id: string;
    title: string;
    description?: string;
    status: TaskStatus;
    priority: number;
    assigned_agent_id?: string;
    project_id?: string;
    auto_approve: boolean;
    position: number;
    task_number: number;
    simple_id: string;
    pr_urls: string[];
    workflow_run_id?: string;
    created_at: string;
    updated_at: string;
}

export interface Session {
    id: string;
    name?: string;
    agent_id: string;
    task_id?: string;
    worktree_id?: string;
    status: SessionStatus;
    resume_session_id?: string;
    prompt?: string;
    result_summary?: string;
    started_at?: string;
    completed_at?: string;
    created_at: string;
    updated_at: string;
}

export interface Worktree {
    id: string;
    agent_id?: string;
    session_id?: string;
    repo_path: string;
    worktree_path: string;
    branch_name: string;
    status: WorktreeStatus;
    created_at: string;
    updated_at: string;
}

export interface Project {
    id: string;
    name: string;
    description?: string;
    task_prefix: string;
    task_counter: number;
    created_at: string;
    updated_at: string;
}

export interface ProjectRepository {
    id: string;
    project_id: string;
    local_path: string;
    remote_url?: string;
    role: RepositoryRole;
    display_name?: string;
    created_at: string;
    updated_at: string;
}

export interface ProjectInstruction {
    id: string;
    project_id: string;
    title: string;
    content: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface Workflow {
    id: string;
    name: string;
    definition: WorkflowDefinition;
    created_at: string;
    updated_at: string;
}

export interface WorkflowDefinition {
    steps: WorkflowStepDefinition[];
}

export interface WorkflowStepDefinition {
    step_type: WorkflowStepType;
    name: string;
    prompt_template?: string;
    max_retries?: number;
}

export interface WorkflowRun {
    id: string;
    workflow_id: string;
    task_id: string;
    status: WorkflowRunStatus;
    current_step_index: number;
    iteration_count: number;
    main_session_id?: string;
    created_at: string;
    updated_at: string;
}

export interface WorkflowStepOutput {
    id: string;
    workflow_run_id: string;
    step_index: number;
    step_type: WorkflowStepType;
    output?: string;
    attempt: number;
    status: WorkflowStepStatus;
    session_id?: string;
    created_at: string;
}

export interface SessionLog {
    id: number;
    session_id: string;
    log_type: LogType;
    content: string;
    timestamp: string;
}

// ---------------------------------------------------------------------------
// Request types
// ---------------------------------------------------------------------------

export interface CreateTaskRequest {
    title: string;
    description?: string;
    priority?: number;
    status?: TaskStatus;
    project_id?: string;
    assigned_agent_id?: string;
}

export interface UpdateTaskRequest {
    title?: string;
    description?: string;
    priority?: number;
    status?: TaskStatus;
    position?: number;
    project_id?: string;
    assigned_agent_id?: string;
}

export interface AssignTaskRequest {
    agent_id: string;
}

export interface MoveTaskRequest {
    status: TaskStatus;
    position?: number;
}

export interface CreateAgentRequest {
    name: string;
    agent_type?: AgentType;
}

export interface CreateSessionRequest {
    agent_id: string;
    task_id: string;
    prompt: string;
    repo_path: string;
    name?: string;
    auto_approve?: boolean;
    /** Internal: close stdin after Result so process exits after one turn. Used by workflow engine. */
    exit_on_result?: boolean;
}

export interface ResumeSessionRequest {
    prompt?: string;
    /** Internal: close stdin after Result so process exits after one turn. Used by workflow engine. */
    exit_on_result?: boolean;
}

export interface SendSessionInputRequest {
    message: string;
}

export interface CreateProjectRequest {
    name: string;
    description?: string;
}

export interface UpdateProjectRequest {
    name?: string;
    description?: string;
}

export interface AddProjectRepositoryRequest {
    local_path: string;
    remote_url?: string;
    role?: RepositoryRole;
    display_name?: string;
}

export interface UpdateProjectRepositoryRequest {
    local_path?: string;
    remote_url?: string;
    role?: RepositoryRole;
    display_name?: string;
}

export interface AddProjectInstructionRequest {
    title: string;
    content: string;
    sort_order?: number;
}

export interface UpdateProjectInstructionRequest {
    title?: string;
    content?: string;
    sort_order?: number;
}

export interface CreateWorkflowRequest {
    name: string;
    definition: WorkflowDefinition;
}

export interface UpdateWorkflowRequest {
    name?: string;
    definition?: WorkflowDefinition;
}

export interface StartWorkflowRequest {
    workflow_id: string;
}

export interface WorkflowDecisionRequest {
    approved: boolean;
    comments?: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface AgentHealth {
    agent_id: string;
    is_installed: boolean;
    is_authenticated: boolean;
    version?: string;
}

export interface StartTaskResponse {
    task: Task;
    session: Session;
}

// ---------------------------------------------------------------------------
// Filesystem types
// ---------------------------------------------------------------------------

export interface DirEntry {
    name: string;
    path: string;
    is_dir: boolean;
}

export interface BrowseResponse {
    current_path: string;
    parent?: string;
    entries: DirEntry[];
}

// ---------------------------------------------------------------------------
// WebSocket types
// ---------------------------------------------------------------------------

export type WsEvent =
    | { type: "AgentStatusChanged"; payload: { agent_id: string; status: AgentStatus } }
    | { type: "AgentHealthUpdated"; payload: { agent_id: string; health: AgentHealth } }
    | { type: "TaskCreated"; payload: Task }
    | { type: "TaskUpdated"; payload: Task }
    | { type: "TaskDeleted"; payload: { task_id: string } }
    | { type: "TaskMoved"; payload: { task_id: string; from_status: TaskStatus; to_status: TaskStatus } }
    | { type: "SessionStarted"; payload: { session_id: string; agent_id: string; task_id?: string } }
    | { type: "SessionCompleted"; payload: { session_id: string; result_summary?: string; claude_session_id?: string } }
    | { type: "SessionFailed"; payload: { session_id: string; error: string; claude_session_id?: string } }
    | { type: "SessionPaused"; payload: { session_id: string } }
    | { type: "SessionOutput"; payload: { session_id: string; log_type: LogType; content: string } }
    | { type: "SessionResumeIdCaptured"; payload: { session_id: string; claude_session_id: string } }
    | { type: "WorktreeCreated"; payload: Worktree }
    | { type: "WorktreeDeleted"; payload: { worktree_id: string } }
    | { type: "ProjectCreated"; payload: Project }
    | { type: "ProjectUpdated"; payload: Project }
    | { type: "ProjectDeleted"; payload: { project_id: string } }
    | { type: "ProjectRepositoryAdded"; payload: { project_id: string; repository: ProjectRepository } }
    | { type: "ProjectRepositoryRemoved"; payload: { project_id: string; repository_id: string } }
    | { type: "ProjectInstructionAdded"; payload: { project_id: string; instruction: ProjectInstruction } }
    | { type: "ProjectInstructionUpdated"; payload: { project_id: string; instruction: ProjectInstruction } }
    | { type: "ProjectInstructionRemoved"; payload: { project_id: string; instruction_id: string } }
    | { type: "WorkflowRunUpdated"; payload: WorkflowRun }
    | { type: "WorkflowStepChanged"; payload: { workflow_run_id: string; step: WorkflowStepOutput } }
    | { type: "WorkflowRunCompleted"; payload: { workflow_run_id: string; task_id: string } }
    | { type: "WorkflowWaitingForHuman"; payload: { workflow_run_id: string; task_id: string; step_index: number } };

export type WsCommand =
    | { type: "SubscribeSession"; payload: { session_id: string } }
    | { type: "UnsubscribeSession"; payload: { session_id: string } }
    | { type: "SendInput"; payload: { session_id: string; message: string } }
    | { type: "Ping" };
