// Auto-generated by ts-rs. DO NOT EDIT.
// This file will be overwritten by `pnpm run generate-types`

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type AgentType = "claude_code";
export type AgentStatus = "idle" | "busy" | "error" | "offline";
export type AuthStatus = "unknown" | "authenticated" | "unauthenticated";
export type TaskStatus = "backlog" | "in_progress" | "waiting" | "done";
export type SessionStatus = "created" | "running" | "paused" | "completed" | "failed";
export type WorktreeStatus = "active" | "stale" | "deleted";
export type LogType = "stdout" | "stderr" | "control" | "status";

// ---------------------------------------------------------------------------
// Model structs
// ---------------------------------------------------------------------------

export interface Agent {
    id: string;
    name: string;
    agent_type: AgentType;
    executable_path?: string;
    status: AgentStatus;
    auth_status: AuthStatus;
    last_heartbeat?: string;
    created_at: string;
    updated_at: string;
}

export interface Task {
    id: string;
    title: string;
    description?: string;
    status: TaskStatus;
    priority: number;
    assigned_agent_id?: string;
    repo_path?: string;
    auto_approve: boolean;
    position: number;
    created_at: string;
    updated_at: string;
}

export interface Session {
    id: string;
    agent_id: string;
    task_id?: string;
    worktree_id?: string;
    status: SessionStatus;
    resume_session_id?: string;
    prompt?: string;
    result_summary?: string;
    started_at?: string;
    completed_at?: string;
    created_at: string;
    updated_at: string;
}

export interface Worktree {
    id: string;
    agent_id?: string;
    session_id?: string;
    repo_path: string;
    worktree_path: string;
    branch_name: string;
    status: WorktreeStatus;
    created_at: string;
    updated_at: string;
}

export interface SessionLog {
    id: number;
    session_id: string;
    log_type: LogType;
    content: string;
    timestamp: string;
}

// ---------------------------------------------------------------------------
// Request types
// ---------------------------------------------------------------------------

export interface CreateTaskRequest {
    title: string;
    description?: string;
    priority?: number;
    status?: TaskStatus;
    assigned_agent_id?: string;
    repo_path?: string;
}

export interface UpdateTaskRequest {
    title?: string;
    description?: string;
    priority?: number;
    status?: TaskStatus;
    position?: number;
    assigned_agent_id?: string;
    repo_path?: string;
}

export interface AssignTaskRequest {
    agent_id: string;
}

export interface MoveTaskRequest {
    status: TaskStatus;
    position?: number;
}

export interface CreateAgentRequest {
    name: string;
    agent_type?: AgentType;
}

export interface CreateSessionRequest {
    agent_id: string;
    task_id: string;
    prompt: string;
    repo_path: string;
    auto_approve?: boolean;
}

export interface ResumeSessionRequest {
    prompt?: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface AgentHealth {
    agent_id: string;
    is_installed: boolean;
    is_authenticated: boolean;
    version?: string;
}

export interface StartTaskResponse {
    task: Task;
    session: Session;
}

// ---------------------------------------------------------------------------
// WebSocket types
// ---------------------------------------------------------------------------

export type WsEvent =
    | { type: "AgentStatusChanged"; payload: { agent_id: string; status: AgentStatus } }
    | { type: "AgentHealthUpdated"; payload: { agent_id: string; health: AgentHealth } }
    | { type: "TaskCreated"; payload: Task }
    | { type: "TaskUpdated"; payload: Task }
    | { type: "TaskDeleted"; payload: { task_id: string } }
    | { type: "TaskMoved"; payload: { task_id: string; from_status: TaskStatus; to_status: TaskStatus } }
    | { type: "SessionStarted"; payload: { session_id: string; agent_id: string; task_id?: string } }
    | { type: "SessionCompleted"; payload: { session_id: string; result_summary?: string } }
    | { type: "SessionFailed"; payload: { session_id: string; error: string } }
    | { type: "SessionPaused"; payload: { session_id: string } }
    | { type: "SessionOutput"; payload: { session_id: string; log_type: LogType; content: string } }
    | { type: "WorktreeCreated"; payload: Worktree }
    | { type: "WorktreeDeleted"; payload: { worktree_id: string } };

export type WsCommand =
    | { type: "SubscribeSession"; payload: { session_id: string } }
    | { type: "UnsubscribeSession"; payload: { session_id: string } }
    | { type: "Ping" };
