// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryRole } from "./RepositoryRole";

export type AddProjectRepositoryRequest = { local_path: string, remote_url: string | null, role: RepositoryRole | null, display_name: string | null, };
