// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentHealth = { agent_id: string, is_installed: boolean, is_authenticated: boolean, version: string | null, };
