// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { AgentType } from "./AgentType";
import type { AuthStatus } from "./AuthStatus";

export type Agent = { id: string, name: string, agent_type: AgentType, executable_path: string | null, status: AgentStatus, auth_status: AuthStatus, last_heartbeat: string | null, created_at: string, updated_at: string, };
