// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

export type BrowseResponse = { current_path: string, parent: string | null, entries: Array<DirEntry>, };
