// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type CreateTaskRequest = { title: string, description: string | null, priority: number | null, status: TaskStatus | null, assigned_agent_id: string | null, repo_path: string | null, };
