// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSessionRequest = { agent_id: string, task_id: string, prompt: string, repo_path: string, name: string | null, auto_approve: boolean | null, exit_on_result: boolean, };
