// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSessionRequest = { agent_id: string, task_id: string, prompt: string, repo_path: string, auto_approve: boolean | null, 
/**
 * When true, close stdin after the agent produces a Result so the process
 * exits after one turn. Used internally by the workflow engine.
 */
exit_on_result: boolean, };
