// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";

export type CreateAgentRequest = { name: string, agent_type: AgentType | null, };
