// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, description: string | null, task_prefix: string, task_counter: number, created_at: string, updated_at: string, };
