// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryRole } from "./RepositoryRole";

export type ProjectRepository = { id: string, project_id: string, local_path: string, remote_url: string | null, role: RepositoryRole, display_name: string | null, created_at: string, updated_at: string, };
