// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type Session = { id: string, name: string | null, agent_id: string, task_id: string | null, worktree_id: string | null, status: SessionStatus, resume_session_id: string | null, prompt: string | null, result_summary: string | null, started_at: string | null, completed_at: string | null, created_at: string, updated_at: string, };
