// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogType } from "./LogType";

export type SessionLog = { id: bigint, session_id: string, log_type: LogType, content: string, timestamp: string, };
