// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";
import type { Task } from "./Task";

export type StartTaskResponse = { task: Task, session: Session, };
