// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, title: string, description: string | null, status: TaskStatus, priority: number, assigned_agent_id: string | null, project_id: string | null, auto_approve: boolean, position: number, task_number: number, simple_id: string, pr_urls: Array<string>, workflow_run_id: string | null, created_at: string, updated_at: string, };
