// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProjectInstructionRequest = { title: string | null, content: string | null, sort_order: number | null, };
