// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryRole } from "./RepositoryRole";

export type UpdateProjectRepositoryRequest = { local_path: string | null, remote_url: string | null, role: RepositoryRole | null, display_name: string | null, };
