// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeStatus } from "./WorktreeStatus";

export type Worktree = { id: string, agent_id: string | null, session_id: string | null, repo_path: string, worktree_path: string, branch_name: string, status: WorktreeStatus, created_at: string, updated_at: string, };
