// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

export type WorkflowRun = { id: string, workflow_id: string, task_id: string, status: WorkflowRunStatus, iteration_count: number, activated_steps: Array<string>, created_at: string, updated_at: string, };
