// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDefinition } from "./WorkflowDefinition";

export type Workflow = { id: string, project_id: string, name: string, definition: WorkflowDefinition, created_at: string, updated_at: string, };
