// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStepStatus = "pending" | "running" | "waiting_for_human" | "completed" | "rejected" | "failed";
