// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionMode } from "./SessionMode";
import type { WorkflowStepType } from "./WorkflowStepType";

export type WorkflowStepDefinition = { id: string, step_type: WorkflowStepType, name: string, prompt_template: string | null, depends_on: Array<string>, on_approve: string | null, on_reject: string | null, max_retries: number | null, loop_back_to: string | null, session_mode: SessionMode | null, };
