// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStepType = "plan" | "human_gate" | "implement" | "pr_review" | "human_review";
