// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStepType } from "./WorkflowStepType";

export type WorkflowStepDefinition = { step_type: WorkflowStepType, name: string, prompt_template: string | null, max_retries: number | null, };
