// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowResumeAction } from "./WorkflowResumeAction";

export type WorkflowResumeRequest = { step_id: string | null, action: WorkflowResumeAction | null, };
