// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

export type WorkflowRun = { id: string, workflow_id: string, task_id: string, status: WorkflowRunStatus, current_step_index: number, iteration_count: number, main_session_id: string | null, created_at: string, updated_at: string, };
