// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WsCommand = { "type": "SubscribeSession", "payload": { session_id: string, } } | { "type": "UnsubscribeSession", "payload": { session_id: string, } } | { "type": "Ping" };
