// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHealth } from "./AgentHealth";
import type { AgentStatus } from "./AgentStatus";
import type { LogType } from "./LogType";
import type { Task } from "./Task";
import type { TaskStatus } from "./TaskStatus";
import type { Worktree } from "./Worktree";

export type WsEvent = { "type": "AgentStatusChanged", "payload": { agent_id: string, status: AgentStatus, } } | { "type": "AgentHealthUpdated", "payload": { agent_id: string, health: AgentHealth, } } | { "type": "TaskCreated", "payload": Task } | { "type": "TaskUpdated", "payload": Task } | { "type": "TaskDeleted", "payload": { task_id: string, } } | { "type": "TaskMoved", "payload": { task_id: string, from_status: TaskStatus, to_status: TaskStatus, } } | { "type": "SessionStarted", "payload": { session_id: string, agent_id: string, task_id: string | null, } } | { "type": "SessionCompleted", "payload": { session_id: string, result_summary: string | null, } } | { "type": "SessionFailed", "payload": { session_id: string, error: string, } } | { "type": "SessionPaused", "payload": { session_id: string, } } | { "type": "SessionOutput", "payload": { session_id: string, log_type: LogType, content: string, } } | { "type": "WorktreeCreated", "payload": Worktree } | { "type": "WorktreeDeleted", "payload": { worktree_id: string, } };
